# Generated by Django 4.0b1 on 2021-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "discord_server_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
    ]
